// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUrt9nE18gIiaJIuDChXdAP5dO6H8-2oo',
    appId: '1:746290625033:web:26e596d6b35ac98f3256d8',
    messagingSenderId: '746290625033',
    projectId: 'sanupjongmin',
    authDomain: 'sanupjongmin.firebaseapp.com',
    storageBucket: 'sanupjongmin.firebasestorage.app',
    measurementId: 'G-N90SZR5R3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvvR1jWLg3k3dO4xamOuwEx3SDzCsnfpk',
    appId: '1:746290625033:android:0109f7840a761ec83256d8',
    messagingSenderId: '746290625033',
    projectId: 'sanupjongmin',
    storageBucket: 'sanupjongmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1C0k94eznKFcacGyCURd3CUzRQSWEiY',
    appId: '1:746290625033:ios:e337428575cdd0a03256d8',
    messagingSenderId: '746290625033',
    projectId: 'sanupjongmin',
    storageBucket: 'sanupjongmin.firebasestorage.app',
    iosBundleId: 'com.example.sanupjongmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1C0k94eznKFcacGyCURd3CUzRQSWEiY',
    appId: '1:746290625033:ios:e337428575cdd0a03256d8',
    messagingSenderId: '746290625033',
    projectId: 'sanupjongmin',
    storageBucket: 'sanupjongmin.firebasestorage.app',
    iosBundleId: 'com.example.sanupjongmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUrt9nE18gIiaJIuDChXdAP5dO6H8-2oo',
    appId: '1:746290625033:web:4752f4e80fa4626b3256d8',
    messagingSenderId: '746290625033',
    projectId: 'sanupjongmin',
    authDomain: 'sanupjongmin.firebaseapp.com',
    storageBucket: 'sanupjongmin.firebasestorage.app',
    measurementId: 'G-SSK7RL852Z',
  );
}
